name: Tests

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: python -m pip install --upgrade pip
    - name: Build wheel
      run: python -m pip wheel -w dist/ .
    - name: Archive wheel
      uses: actions/upload-artifact@v4
      with:
        name: python-wheel
        path: dist/cocoviz*.whl
  test:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12"]
    runs-on: ${{matrix.runs-on}}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install ruff pytest
    - name: Install package
      run: python -m pip install .
    - name: Lint with ruff
      run: ruff check --output-format=github .
    - name: Run tests
      run: python -m pytest tests/